### ISSUE TITLE
执行train.py的时候报错

### ISSUE THREAD

**Issue by ohblue** [Starry-OvO/rotate-captcha-crack#10]
```
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    train_loss = total_train_loss / steps
ZeroDivisionError: float division by zero
```

**Comment by Starry-OvO** [comment]
确定图片文件夹里都是jpg后缀的图片文件吗，如果是jpeg或者png的话要修改config.toml

**Comment by ohblue** [comment]
> 确定图片文件夹里都是jpg后缀的图片文件吗，如果是jpeg或者png的话要修改config.toml

都是jpg，config.toml里边也是jpg
print(img_paths)出来的列表也都读取到文件路径了
还是这个错误

**Comment by ohblue** [comment]
使用 Landscape-Dataset 图集训练的时候，会报这个错：
```
Traceback (most recent call last):
  File ".\train.py", line 83, in <module>
    source: Tensor = source.to(device=device)
AttributeError: 'int' object has no attribute 'to'
```

**Comment by Starry-OvO** [comment]
`source`怎么会是int，我这复现不出来
还有训练用的数据量不到64的话直接就droplast了，到64的量级才能读出一个batch
