### ISSUE TITLE
找不到文件夹

### ISSUE THREAD

**Issue by Tongmengjun** [Starry-OvO/rotate-captcha-crack#22]
报错：Traceback (most recent call last):
  File "E:\Code\Python\Project\NFT\rotate\rotate-captcha-crack-master\test_captcha.py", line 19, in <module>
    print(WhereIsMyModel(model).with_index(opts.index))
  File "E:\Code\Python\Project\NFT\rotate\rotate-captcha-crack-master\rotate_captcha_crack\model\helper.py", line 61, in with_index
    *_, model_dir = models_dir.iterdir()
  File "E:\Environment\Anaconda\lib\pathlib.py", line 1160, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'models\\RotNetR'
我的models路径为rotate/rotate-captcha-crack-master/rotate_captcha_crack/models

**Comment by Starry-OvO** [comment]
你已经下载并解压了模型吗

**Comment by Tongmengjun** [comment]
> 你已经下载并解压了模型吗

**Comment by Tongmengjun** [comment]
> 你已经下载并解压了模型吗

是的。RotNetR和RotNet都有
